---

- hosts: all
  become: true
  tasks:

  - name: udpate repo index 
    apt:
      update_cache: yes

  - name: install apache2 to package
    apt:
      name: apache2
      state: latest

  - name: add php support 
    apt: 
      name: libapache2-mod-php
      state: latest

  - name: start apache2 service 
    ansible.builtin.service:
      name: apache2
      state: started
