---

- hosts: all
  become: true
  tasks:

  - name: Stop service apache2, if started
    ansible.builtin.service:
      name: apache2
      state: stopped

  - name: install apache2 to package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
      