---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_Cache: yes
    when: ansible_distribution == "Centos"

  - name: install updates (Ubuntu)
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: yes
  tasks:

  - name: install apache and phph for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apacjer amd ühüh for Centos servers
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Centos"

  - name: copy default html file for site 
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Centos)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Centos"

  - name: install mariadb for Ubuntu servers
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

